stages:
  -code_lint

default:
  tags:
    - light

before_script:
  - apt-get update -qy

include:
  - project: "internal-public/ci-templates"
    ref: main
    file:
      - "code_lint/python_check.yaml"