---
- name: Set up CTFd
  hosts: ctfd
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - git
        state: present

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add docker directory
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: "{{ ansible_distribution_release }}"
        components:
          - stable
        architectures:
          - amd64
        signed_by: /etc/apt/keyrings/docker.asc
        state: present
        enabled: true

    - name: Update apt cache after adding Docker repository
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Clone ctfd git repo
      ansible.builtin.git:
        repo: 'https://github.com/CTFd/CTFd.git'
        dest: /opt/CTFd
        update: true


    - name: Generate secret key
      ansible.builtin.set_fact:
        ctfd_secret_key: "{{ lookup('ansible.builtin.password', '/home/debain/.ctfd-secret-key length=64 chars=ascii_letters,digits') }}"
      no_log: true

    - name: Insert secret key into docker compose
      ansible.builtin.lineinfile:
        path: /opt/CTFd/docker-compose.yml
        insertafter: "environment:"
        regexp: '^\s*-\s*SECRET_KEY=' #idempotency checks
        line: '      - SECRET_KEY={{ ctfd_secret_key }}'

    - name: Start CTFd
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /opt/CTFd
