ludus:
  - vm_name: "{{ range_id }}-ctfd"
    hostname: "{{ range_id }}-ctfd"
    template: debian-12-x64-server-template
    vlan: 10
    ip_last_octet: 10   #last num on the ip
    ram_gb: 4
    cpus: 2
    linux: true
    roles:
      - name: alicev.ctfd-setup

network:
  rules:
    - name: Allow ctfd VM to reach Ludus host
      vlan_src: 10
      vlan_dst: public
      protocol: tcp
      ports: 8080
      action: ACCEPT

router:
  iptables_commands:
    - iptables -I LUDUS_DEFAULTS 1 -s 10.1.10.10 -d 192.168.2.100 -p tcp --dport 8080 -j ACCEPT
