ludus:
  - vm_name: "{{ range_id }}-ctfd"
    hostname: "{{ range_id }}-ctfd"
    template: debian-12-x64-server-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    linux: true
    roles:
      - name: ctfd-setup
