---
- name: Pin Python interpreter for this host
  ansible.builtin.set_fact:
    ansible_python_interpreter: /usr/bin/python3

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - git
      - python3-debian
      - python3-pip
    state: present
    update_cache: true

- name: Install python-dotenv
  ansible.builtin.pip:
    name: python-dotenv

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add docker directory
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_distribution_release }}"
    components:
      - stable
    architectures:
      - amd64
    signed_by: /etc/apt/keyrings/docker.asc
    state: present
    enabled: true

- name: Update apt cache after adding Docker repository
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Clone ctfd git repo
  ansible.builtin.git:
    repo: 'https://github.com/CTFd/CTFd.git'
    dest: /opt/CTFd
    update: true
    force: true


- name: Generate secret key
  ansible.builtin.set_fact:
    ctfd_secret_key: "{{ lookup('ansible.builtin.password', '/tmp/.ctfd-secret-key length=64 chars=ascii_letters,digits') }}"
  no_log: false

- name: Insert secret key into docker compose
  ansible.builtin.lineinfile:
    path: /opt/CTFd/docker-compose.yml
    insertafter: '^\s*- REVERSE_PROXY=true'
    regexp: '^\s*-\s*SECRET_KEY=' #idempotency checks
    line: '      - SECRET_KEY={{ ctfd_secret_key }}'

- name: Copy plugin into ctfd vm
  ansible.builtin.copy:
    src: ctfd-plugin/
    dest: /opt/CTFd/CTFd/plugins/ctfd-plugin

- name: Start CTFd
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/CTFd


